### ISSUE TITLE
consent string with no consent but cookie set

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#1694]
Hi,

I am calling the setuid endpoint with a consent string which contains no consent information at all about my vendor id, but a cookie is dropped anyway. I did not changed the gdpr.enabled value so it's true by default according to config.go. In my pbs.yaml I have these settings about gdpr : 
```
gdpr:
        host_vendor_id: 791
        timeouts_ms.init_vendorlist_fetches: 1000
        timeouts_ms.active_vendorlist_fetch: 1000
```
I am not so sure about the effets of these defaults params in config.go : 
```
        v.SetDefault("gdpr.tcf2.purpose1.enabled", true)
        v.SetDefault("gdpr.tcf2.purpose2.enabled", true)
        v.SetDefault("gdpr.tcf2.purpose4.enabled", true)
        v.SetDefault("gdpr.tcf2.purpose7.enabled", true)
        v.SetDefault("gdpr.tcf2.special_purpose1.enabled", true)
        v.SetDefault("gdpr.tcf2.purpose_one_treatement.enabled", true)
        v.SetDefault("gdpr.tcf2.purpose_one_treatement.access_allowed", true)
```
Does it means that it forces these purpose to true regardless of the consent string received ?
