### ISSUE TITLE
gdpr no consent : bidders not called even with enforcement

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#2233]
Hi,

I am trying to force prebid to call bidders when gdpr consent was declined but it does not seem to work. I see nothing in prebid-server response `responsetimemillis` so I assume my enforcement fails. Here is my current gdpr config :
```
gdpr:
    host_vendor_id: _my_vendor_id_
    timeouts_ms.init_vendorlist_fetches: 1000
    timeouts_ms.active_vendorlist_fetch: 1000
    default_value: 1
    tcf2:
        purpose1:
            enforce_vendors: false
        purpose2:
            enforce_vendors: false
        purpose3:
            enforce_vendors: false
        purpose4:
            enforce_vendors: false
        purpose5:
            enforce_vendors: false
        purpose6:
            enforce_vendors: false
        purpose7:
            enforce_vendors: false
        purpose9:
            enforce_vendors: false
        purpose9:
            enforce_vendors: false
        purpose10:
            enforce_vendors: false
```
Could you please tell me what I should do to make sure my bidders are called without gdpr consent ?
