### ISSUE TITLE
new installation - vendor-list-v143.json

### ISSUE THREAD

**Issue by redimongo** [prebid/prebid-server#2252]
I have just done a fresh install of prebid-server and for some reason I am getting this error which I can't seem to find away to fix it.

```
vendorlist-fetching.go:115] Error calling GET https://vendor-list.consensu.org/v2/archives/vendor-list-v143.json. Cookie syncs may be affected: context deadline exceeded
```

In my pbs.yml I have it set as
```
gdpr:
  default_value: "0"
  timeouts_ms:
    init_vendorlist_fetches: 5000
    active_vendorlist_fetch: 5000
```

Any suggestions please.
