### ISSUE TITLE
How to correctly query stored_requests and stored_responses from Postgres? 

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-server#2482]
I found 2 examples.

1. https://docs.prebid.org/prebid-server/features/pbs-storedreqs-go.html
```
stored_requests:
  postgres:
    host: localhost
    port: 5432
    user: db-username
    dbname: database-name
    query: SELECT id, requestData, 'request' as type FROM stored_requests WHERE id in %REQUEST_ID_LIST% UNION ALL SELECT id, impData, 'imp' as type FROM stored_imps WHERE id in %IMP_ID_LIST%;
```
2. https://docs.prebid.org/prebid-server/hosting/pbs-database.html#stored-responses
```
settings:
  database:
    type: mysql
    stored-requests-query: SELECT uuid, config, 'request' as dataType FROM stored_requests WHERE uuid IN (%REQUEST_ID_LIST%) UNION ALL SELECT uuid, config, 'imp' as dataType FROM stored_requests WHERE uuid IN (%IMP_ID_LIST%)
```

In the first example, `stored_requests` is the root element, but in the second example, `settings` is the root element. Which one should I follow?

And most importantly, what about stored_responses? By referring to both example, I tried the following:
```
stored_responses:
  postgres:
    host: localhost
    port: 5432
    user: db-username
    dbname: database-name
    query: SELECT id, responseData as type FROM stored_responses WHERE id in (%RESPONSE_ID_LIST%);
```

and I got `Invalid bid response: Code 400. Invalid request: pq: got 1 parameters but the statement requires 0`.

What is the correct pbs.yaml configuration to query from database?

**Comment by VeronikaSolovei9** [comment]
@clho40 Thank you for the question! 
We recently merged, but not yet deployed functionality related to Postgres and MySql support. 
Current config can only be like this: 
```
stored_responses:
   postgres:
      connection: 
          host: localhost
          port: 5432
           user: db-username
...
```

After this change is deployed we will support both MySQL and Postgres and both config types. It will be backwards compatible with current config. 
This will be a valid config: 
```
stored_responses:
    postgres:
         connection:
                driver: postgres
                host: localhost
                port: 5432
                user: db-username
...
```
This will be a valid config too (for Postgres):
```
stored_responses:
    database:
         connection:
                driver: postgres
                host: localhost
                port: 5432
                user: db-username
...
```
This will be a valid config too (for MySQL):
```
stored_responses:
    database:
         connection:
                driver: mysql
                host: localhost
                port: 5432
                user: db-username
...
```

For your queries, try to follow this example:
```
// !!! I put "queryPostgres" and  "queryMysql" so you can see how queries will look like depends on your driver, 
// in actual config it's just "query"

//fetch list of stored responses
"fetcher": {
        "queryPostgres": "SELECT uuid AS id, config as data, 'response' as dataType FROM storedresponse_config WHERE uuid IN %ID_LIST%;",
        "queryMysql": "SELECT uuid AS id, config as data, 'response' as dataType FROM storedresponse_config WHERE uuid IN $ID_LIST;"
      },

// init list of stored responses at the server startup, I think this is where your issue comes from, 
// this query doesn't expect any parameters, it just fetches everything. Query is the same for Postgres and MySQL
 "initialize_caches": {
        "timeout_ms": 5000,
        "query": "SELECT uuid AS id, config as data, 'response' as dataType FROM storedresponse_config;"
      },

// this config has queries to fetch newly created or updated stored responses without server restart. 
// poll_for_updates query executes by PBS core every 15 seconds (in this example) and needs to keep track of when 
// were the previous changes fetched to get only data that was updated during last 15 seconds. 
// This is why  poll_for_updates query needs a parameter
"poll_for_updates": {
        "refresh_rate_seconds": 15,
        "timeout_ms": 1000,
        "queryPostgres": "SELECT uuid AS id, config as data, 'response' as dataType FROM storedresponse_config WHERE updated_at > $1;",
        "queryMsql": "SELECT uuid AS id, config as data, 'response' as dataType FROM storedresponse_config WHERE updated_at > $LAST_UPDATED;"
      }
```

Hope it helped. Please ask if you have more questions, I know fetcher configs can be tricky

**Comment by clho40** [comment]
Hello @VeronikaSolovei9 , thank you for your detailed response! It's super helpful! I guess my connection config works and I'll leave it as it is for now until the new changes are deployed!

And regarding the query, I am still confused. I have a pbs.yaml in my root directory:
```
gdpr:
  enabled: true
  default_value: "0"
  timeouts_ms:
    init_vendorlist_fetches: 5000
    active_vendorlist_fetch: 5000
  tcf2:
    enabled: true
stored_requests:
  postgres:
    connection:
      host: 11.111.11.111
      port: 5432
      user: postgres
      password: postgres
      dbname: prebid
    fetcher:
      query: SELECT id, requestData, 'request' as type FROM stored_requests WHERE id in (%REQUEST_ID_LIST%) UNION ALL SELECT id, impData, 'imp' as type FROM stored_imps WHERE id in (%IMP_ID_LIST%);
stored_responses:
  postgres:
    connection:
      host: 11.111.11.111
      port: 5432
      user: postgres
      password: postgres
      dbname: prebid
    fetcher:
      query: SELECT id, responseData as data, 'response' as dataType FROM stored_responses WHERE id in (%RESPONSE_ID_LIST%);
adapters:
  huaweiads:
    disabled: false
cache:
  host: '11.111.11.111:2424'
  scheme: 'http'
```

My questions are:
1. Are there any obsolete configurations?
2. Is `%RESPONSE_ID_LIST%` replaced with `ID_LIST`?
