### ISSUE TITLE
Bidder geographic scope for usersync

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3102]
(split out of #2985)

We would like for bidders to be able to define when they will respond to usersyncs. This matters mostly when the cooperative sync option is in use, but can matter more generally for multinational publishers.

The /cookie_sync endpoint does not do a geographic lookup, and we would prefer that it didn't. What it does have is privacy regulation info: GDPR and GPP scope flags.

## Requirements

1. Allow bidders to declare they don't want to sync when GDPR is in scope
2. Allow bidders to declare they don't want to sync in a given GPP SID
3. the /cookie_sync endpoint honors these declarations.
4. (For PBS-Java, which has refactored /cookie_sync) If a bidder would have been eligible for syncing but is removed for this reason, return a "bidder regulation scope" warning when in debug mode.

## Proposed Bidder Config

To generalize the concept of letting bidders declare when they don't want to sync, a new `skipwhen` config block is suggested:

```
adapter:
    bidderA:
        usersync:
            skipwhen:
                gdpr: true
                gpp_sid:
                    - 2
```
