### ISSUE TITLE
Account level targeting config

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3147]
It's not optimal that stored requests have to contain ext.prebid.targeting values for AMP and SDK scenarios. This creates a need to update many DB entries if there's a change (e.g. in how they want deals prioritized). It would be more convenient to have the account-level config store the target settings.

Suggested config:

```
auction:
    truncate-target-attr: 20      // would like to move this under targeting
    targeting:
        includewinners: true/false
        includebidderkeys: true/false
        includeformat: true/false
        preferdeals: true/false
        alwaysincludedeals: true/false
```

And, as usual, if the value is seen in both the request/stored-request AND config, request takes precedence.
