### ISSUE TITLE
Bug: adapter specific `gpp-supported` config-field is not getting honoured even though adapter dont have `gpp-supported` config set in the host specific pbs.yaml file

### ISSUE THREAD

**Issue by ashishshinde-pubm** [prebid/prebid-server#3177]
Currently as per the code `gpp-supported` is supported only if adapter has entry in the host specific pbs.yaml
Current code does not honour the  `gpp-supported` flag set in the adapter specific yaml file (bidder-info/adapter.yaml). 
This is because we have missed to copy the values in `applyBidderInfoConfigOverrides` function. 

Example - 
pbs.yaml (host file) has following entry for pubmatic adapter
```
adapters:
  pubmatic:
    endpoint: https://hbopenbid.pubmatic.com/translator?source=prebid-server
 
```  
bidder-info/pubmatic.yaml is like below
```
endpoint: "https://hbopenbid.pubmatic.com/translator?source=prebid-server"
maintainer:
  email: "header-bidding@pubmatic.com"
  ...
  ...
openrtb:
  gpp-supported: true

```
In above case, prebid will not honour the `gpp-supported` config field.
PR - https://github.com/prebid/prebid-server/pull/3178 fix this issue
