### ISSUE TITLE
WARN 13:  Account not specified

### ISSUE THREAD

**Issue by dzesm** [prebid/prebid-server#3332]
WARN 13 --- o.p.s.a.r.Ortb2RequestFactory : Account not specified, Url: http://.../openrtb2/auction (removed the domain)
and Referer: null

The account id is setup in yaml file
      accounts:
        - id: 1111 (not real id)
          status: active
    
And then I set it in s2sConfig
     accountId: '1111'
     
     
 What could be the problem here? I see the account Id in pbjs config, yet the error persists.

**Comment by Net-burst** [comment]
@dzesm could you please provide more info? The error that you are seeing means that PBS failed to find the account in the incoming request. You want to be sure that the account is being passed in the PBS call. Could you please provide the captured request?

**Comment by bretg** [comment]
site.publisher.id needs to be a string

none of the other account ID locations matter - just {site,app,dooh}.publisher.id.

I'd forgotten about ext.prebid.account -- looks like that was either never implemented or got dropped along the way. Will bring it up in committee.

**Comment by Net-burst** [comment]
@dzesm hi. I couldn't reproduce your issue, unfortunately. 

First and foremost, PBS needs to be restarted after yaml file changes. Here's the steps that I took when I tried to reproduce your issue:
- I'm running the Prebid Server using an example from the README.md: `java -jar target/prebid-server.jar --spring.config.additional-location=sample/prebid-config.yaml`
- `sample/prebid-config.yaml` loads a separate account config file `sample/sample-app-settings.yaml`. This property controls which file will be used and is defined in the `sample/prebid-config.yaml`: `settings.filesystem.settings-filename`
- For the purity of the experiment, I've also set `settings.enforce-valid-account` to `true`. This makes PBS refuse any requests that don't carry a valid configured account with the **HTTP 401** error. My resulting `sample/prebid-config.yaml` file looks like this:
``` yaml
status-response: "ok"
adapters:
  appnexus:
    enabled: true
  ix:
    enabled: true
  openx:
    enabled: true
  pubmatic:
    enabled: true
  rubicon:
    enabled: true
metrics:
  prefix: prebid
cache:
  scheme: http
  host: localhost
  path: /cache
  query: uuid=
settings:
  enforce-valid-account: true
  generate-storedrequest-bidrequest-id: true
  filesystem:
    settings-filename: sample/sample-app-settings.yaml
    stored-requests-dir: sample/stored
    stored-imps-dir: sample/stored
    stored-responses-dir: sample/stored
    categories-dir:
gdpr:
  default-value: 1
  vendorlist:
    v2:
      cache-dir: /var/tmp/vendor2
    v3:
      cache-dir: /var/tmp/vendor3
admin-endpoints:
  logging-changelevel:
    enabled: true
    path: /logging/changelevel
    on-application-port: true
    protected: false
```
- After all this, I added a new account to the `sample/sample-app-settings.yaml` file. Here's the contents of my resulting file:
``` yaml
accounts:
  - id: 1001
    status: active
    auction:
      price-granularity: low
    privacy:
      ccpa:
        enabled: true
      gdpr:
        enabled: true
    cookie-sync:
      default-limit: 8
      max-limit: 15
      coop-sync:
        default: true
  - id: 111111
    status: active
```
- Run or restart PBS and send the Auction Request. I had to modify your original JSON file to fix it's syntax (excess or missing commas), but everything else was left unchanged:
``` json
```
