### ISSUE TITLE
Collect and enforce bidder currency requirement

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3746]
Our advice for bid adapters related to currency is at https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html#currency .

This works fine as long as the bidder has their own adapter, but doesn't work if they're an alias of the 'generic' bidder.

I propose adding a currency setting to the YAML:

```
adapters:
  generic:
    endpoint: https://
    aliases:
      bidderA:
        enabled: true
        endpoint: ...
        meta-info:
          currency-accepted:
            - USD
            - CAD
          maintainer-email: ...
          site-media-types:
            - banner
          vendor-id: 999999
```
If the bidder defines `currency-accepted` and $.cur doesn't intersect, then don't call this bidder/alias. Log a seatnonbid code 200 "Request blocked - General"
