### ISSUE TITLE
Preprocess bid requests for valid media types

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#555]
A comment which @muncha put in his adapter code in #538 reminded me of this. It's a good idea, and I realized it wasn't logged anywhere.

In the `static/bidder-info/{bidder}.yaml` files, Bidders describe which types of media types & platforms they support. For example:

```
capabilities:
  app:
    mediaTypes:
      - banner
  site:
    mediaTypes:
      - banner
      - video
```

We should add these into the core auction logic, so that bidders never see requests for types & platforms they're not expecting. It would also centralize the error messages we return to pubs so that we can make them consistent across all the bidders.
