### ISSUE TITLE
cookie_sync responses lack UUID key - potential misconfiguration of host_cookie values?

### ISSUE THREAD

**Issue by afsheenb** [prebid/prebid-server#580]
Hello,

I have two test instances of prebid-server running; one of them returns the following in response to a POST to the `cookie_sync` endpoint:

```
{"uuid":"148781fb-96dc-4cc1-b30b-b7b71c99477f","status":"ok","bidder_status":[]}
```
the other returns responses without the uuid key present, e.g. 
```
{"status":"ok","bidder_status":[]}
```

The only difference between the two instances is the host_cookie stanza defined in pbs.yaml; the non-working instance has the following defined:

```
host_cookie:
  cookie_name: uids //have tried userid and leaving key blank
  family: prebidServer // have tried adnxs, prebid, and leaving key blank
  domain: the-test-domain.com
  opt_out_url: https://the-test-domain.com/optout
  opt_in_url: https://the-test-domain.com/optin
```

I suspect but can't confirm that we aren't providing the correct value for the family key, after going over the logic in `pbs_light.go` and `cookie_sync.go` - but as near as I can tell from the test params in `config_test.go`, setting the family to `prebid` should be all I need to do.

I can confirm that the uuid is being passed along in the request payload, along with an array of bidders, to both test instances. As far as I can tell there are no other differences between the two instances, other than that both have different external_url's defined in pbs.yaml. 

Can you provide some more detail on what sane values for the host_cookie stanza in the YAML configuration should be set to, for a self-hosted instance of prebid-server?

Thanks,

--afsheen
