### ISSUE TITLE
Setting up prebid-server to fetch request from postgresql database

### ISSUE THREAD

**Issue by Guilemon** [prebid/prebid-server#728]
For prebid -server, i've created a postgresql db and added json request data in it, setting the type to 'request' and a string id.

I also added following config in prebid-server, 
```yaml
stored_requests:
  postgres:
    connection:
      dbname: dbname
      host: localhost
      port: 5432
      user: username
      password: password
    fetcher:
      amp_query: SELECT id, data, 'request' as type FROM stored_requests WHERE id in %REQUEST_ID_LIST%;
```
when accessing following endpoint,
`http://localhost:8000/openrtb2/amp?tag_id={id as stored in db}`

i get `Invalid request format: Stored Request with ID not found`

Then checking the log file, i got this:
`No Stored Request support configured. request.imp[i].ext.prebid.storedrequest will be ignored. If you need this, check your app config
`
i also tested the database query and it was returning json stored in the column.

The above config is added at the very beginning of pbs.yaml file, so i don't think it is any wrong formatting issue..

So, am I missing any step in setting up prebid-server to fetch stored-request from database?
